In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [2]:
df260 = pd.read_csv("raw_data/AllPos_acdc_output_bf_260_frames.csv")
spawning = df260.loc[:, ['Cell_ID', 'relative_ID', 'relationship']]
spawning

      Cell_ID  relative_ID relationship
0           1           -1       mother
1           2           -1       mother
2           3           -1       mother
3           1           -1       mother
4           2           -1       mother
...       ...          ...          ...
6839       81           14          bud
6840       82           15          bud
6841       83           56          bud
6842       84           39          bud
6843       85           49          bud

[6844 rows x 3 columns]

In [3]:
class TreeNode:
    def __init__(self, id):
        self.relative_id = id
        self.children = []
    
    def add_child(self, child_node):
        self.children.append(child_node)
    
    def print_tree(self, level=0):
        print(' ' * 4 * level + f'Node {self.relative_id}')
        for child in self.children:
            child.print_tree(level + 1)

In [4]:
root = TreeNode(-1)
# Dictionary to map Cell_IDs to TreeNode instances
node_map = { -1: root }

# Set to keep track of added children
added_children = set()
added_children.add(-1)

In [5]:
for _, frame in spawning.iterrows():
    if frame.Cell_ID not in added_children:
        added_children.add(frame.Cell_ID)
        new_node = TreeNode(frame.Cell_ID)
        parent_node = node_map.get(frame.relative_ID, None)
        
        if parent_node:
            parent_node.add_child(new_node)
            node_map[frame.Cell_ID] = new_node
        else:
            print(f"Parent node with relative_ID {frame.relative_ID} not found for Cell_ID {frame.Cell_ID}")

In [6]:
root.print_tree()

Node -1
    Node 1
        Node 4
            Node 13
                Node 20
                    Node 43
                Node 45
                    Node 67
                Node 73
            Node 21
        Node 7
            Node 32
                Node 60
            Node 47
                Node 75
            Node 64
        Node 11
            Node 30
                Node 56
                    Node 83
            Node 55
        Node 18
    Node 2
        Node 5
            Node 8
                Node 14
                    Node 44
                    Node 81
                Node 25
                    Node 69
                Node 36
                    Node 57
            Node 10
                Node 24
                    Node 38
                        Node 80
                    Node 72
            Node 17
                Node 26
                    Node 49
                        Node 85
                    Node 70
                Node 29
                    Node 46
            Node 22
                Node 34
                    Node 58
                    Node 77
                Node 53
                Node 79
            Node 35
                Node 62
            Node 61
                Node 65
        Node 12
            Node 19
                Node 39
                    Node 84
                Node 66
            Node 48
                Node 54
            Node 68
        Node 28
    Node 3
        Node 6
            Node 15
                Node 33
                    Node 74
                Node 52
                Node 82
            Node 27
                Node 50
            Node 40
                Node 71
            Node 78
        Node 9
            Node 23
                Node 51
            Node 59
        Node 16
            Node 37
        Node 31
            Node 42
        Node 76
    Node 41
        Node 63